"use client";

import { useState, useEffect, useRef, useCallback, Suspense } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import { useAuth } from "@/hooks/use-auth";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { toast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";
import {
  Zap,
  Copy,
  Check,
  FileDown,
  ArrowRight,
  Loader2,
  AlertCircle,
  Sparkles,
  Crown,
  Play,
  LayoutDashboard,
} from "lucide-react";

export default function GeneratePage() {
  return (
    <Suspense
      fallback={
        <div className="min-h-screen flex items-center justify-center">
          <Loader2 className="h-8 w-8 text-muted-foreground animate-spin" />
        </div>
      }
    >
      <GenerateContent />
    </Suspense>
  );
}

const categories = [
  { label: "Romance", icon: "💕", prompts: ["College romance with betrayal twist", "Long-distance love story with misunderstanding", "Arranged marriage turns into love"] },
  { label: "Family Drama", icon: "👨‍👩‍👧‍👦", prompts: ["Saas-bahu revenge drama", "Joint family property dispute", "Father-son conflict over career choice"] },
  { label: "Thriller", icon: "🔪", prompts: ["Mumbai crime thriller", "Kidnapping with unexpected twist", "Serial killer in a small town"] },
  { label: "Comedy", icon: "😂", prompts: ["Flatmates with opposite personalities", "Desi wedding planning chaos", "Boss and intern swap lives"] },
  { label: "Revenge", icon: "🔥", prompts: ["Betrayed best friend seeks revenge", "Business partner backstab story", "Student exposes corrupt teacher"] },
  { label: "Office", icon: "💼", prompts: ["Office romance gone wrong", "Corporate espionage drama", "Intern vs toxic manager showdown"] },
  { label: "Horror", icon: "👻", prompts: ["Haunted hostel room at night", "Village ghost returns for revenge", "Cursed WhatsApp forward"] },
  { label: "College", icon: "🎓", prompts: ["Ragging turns into friendship", "College election dirty politics", "Toppers vs backbenchers rivalry"] },
];

function GenerateContent() {
  const searchParams = useSearchParams();
  const router = useRouter();
  useAuth(); // ensures auth state is tracked
  const initialPrompt = searchParams.get("prompt") || "";

  const [prompt, setPrompt] = useState(initialPrompt);
  const [script, setScript] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);
  const [pdfLoading, setPdfLoading] = useState(false);
  const [remaining, setRemaining] = useState<number | null>(null);
  const [limit, setLimit] = useState<number>(3);
  const [isPro, setIsPro] = useState(false);
  const [generationId, setGenerationId] = useState<string | null>(null);
  const [activeCategory, setActiveCategory] = useState<string | null>(null);
  const [episodes, setEpisodes] = useState(8);
  const [duration, setDuration] = useState("30-60");
  const scriptRef = useRef<HTMLDivElement>(null);
  const hasAutoGenerated = useRef(false);

  const handleGenerate = useCallback(async (promptText?: string) => {
    const text = promptText || prompt;
    if (!text.trim() || loading) return;

    setLoading(true);
    setError("");
    setScript("");

    try {
      const res = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: text.trim(), episodes, duration }),
      });

      const data = await res.json();

      if (!res.ok) {
        setError(data.error || "Generation failed.");
        if (res.status === 429) {
          setRemaining(0);
        }
        return;
      }

      setScript(data.script);
      setRemaining(data.remaining);
      if (data.limit) setLimit(data.limit);
      setIsPro(data.isPro);
      setGenerationId(data.generationId || null);

      // Scroll to output after a brief delay
      setTimeout(() => {
        scriptRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
      }, 100);
    } catch {
      setError("Network error. Please check your connection.");
    } finally {
      setLoading(false);
    }
  }, [prompt, loading, episodes, duration]);

  // Pre-fill prompt from URL but don't auto-generate
  useEffect(() => {
    if (initialPrompt && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      setPrompt(initialPrompt);
    }
  }, [initialPrompt]);

  const handleCopy = async () => {
    if (!script) return;
    try {
      await navigator.clipboard.writeText(script);
      setCopied(true);
      toast("Script copied to clipboard!", "success");
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast("Failed to copy. Try selecting the text manually.", "error");
    }
  };

  const handlePDF = async () => {
    if (!script) return;
    setPdfLoading(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF();

      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.text("DramaScript.ai — Generated Script", 20, 20);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(120);
      doc.text(`Prompt: ${prompt}`, 20, 28);
      doc.text(`Generated: ${new Date().toLocaleDateString("en-IN")}`, 20, 33);

      doc.setTextColor(0);
      doc.setFontSize(10);

      const lines = doc.splitTextToSize(script, 170);
      let y = 42;
      const pageHeight = doc.internal.pageSize.height;

      for (const line of lines) {
        if (y > pageHeight - 20) {
          doc.addPage();
          y = 20;
        }

        if (line.startsWith("## ") || line.startsWith("SERIES TITLE") || line.startsWith("---")) {
          doc.setFont("helvetica", "bold");
          doc.setFontSize(11);
        } else if (line.startsWith("**")) {
          doc.setFont("helvetica", "bold");
          doc.setFontSize(10);
        } else {
          doc.setFont("helvetica", "normal");
          doc.setFontSize(10);
        }

        doc.text(line, 20, y);
        y += 5;
      }

      // Add watermark/footer to every page
      const totalPages = doc.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(160);
        if (!isPro) {
          // Free tier watermark
          doc.text("Generated with DramaScript.ai — Free Tier | Upgrade to Pro for clean exports", 20, pageHeight - 10);
        } else {
          doc.text("Generated with DramaScript.ai", 20, pageHeight - 10);
        }
      }

      doc.save(`dramascript-${Date.now()}.pdf`);
      toast("PDF downloaded successfully!", "success");
    } catch {
      toast("Failed to generate PDF. Please try again.", "error");
    } finally {
      setPdfLoading(false);
    }
  };

  // ── Block parser types ──
  type DialogueLine = { type: "dialogue"; character: string; line: string } | { type: "direction"; text: string };
  type Block =
    | { type: "header"; fields: Record<string, string> }
    | { type: "episode"; number: number; title: string; meta: Record<string, string>; dialogue: DialogueLine[]; cliffhanger?: string; killerLine?: string; creatorTip?: string }
    | { type: "section"; title: string; lines: string[] }
    | { type: "text"; lines: string[] };

  // ── Inline markdown renderer ──
  const renderInline = (text: string) => {
    const parts = text.replace(/\*\*/g, "\x02").replace(/\*/g, "\x03").split(/(\x02[^\x02]+\x02|\x03[^\x03]+\x03)/g);
    return parts.map((p, j) => {
      if (p.startsWith("\x02") && p.endsWith("\x02")) return <strong key={j} className="font-semibold text-foreground">{p.slice(1, -1)}</strong>;
      if (p.startsWith("\x03") && p.endsWith("\x03")) return <em key={j} className="italic">{p.slice(1, -1)}</em>;
      return p;
    });
  };

  const strip = (s: string) => s.replace(/\*\*/g, "").replace(/^\s*[⏱📍🎬💡🎵⚡💥🎯📱]\s*/, "");

  // ── Pass 1: Parse raw script into semantic blocks ──
  const parseScript = (raw: string): Block[] => {
    const sections = raw.split(/\n---\n|\n-{3,}\n|\n━{3,}\n/).map(s => s.trim()).filter(Boolean);
    const blocks: Block[] = [];

    for (const section of sections) {
      const lines = section.split("\n").map(l => l.trim()).filter(Boolean);
      if (!lines.length) continue;

      // Episode block
      const epMatch = lines[0].match(/^##\s*Episode\s*(\d+)\s*:\s*(.*)/i);
      if (epMatch) {
        const ep: Block = { type: "episode", number: parseInt(epMatch[1]), title: epMatch[2], meta: {}, dialogue: [] };
        for (let j = 1; j < lines.length; j++) {
          const l = lines[j];
          // Key-value: **Label:** Value
          const kv = l.match(/^\*\*(.+?):\*\*\s*(.*)/);
          if (kv) {
            const label = strip(kv[1]).toLowerCase();
            const value = kv[2];
            if (/cliffhanger/i.test(label)) ep.cliffhanger = value;
            else if (/killer\s*line/i.test(label)) ep.killerLine = value.replace(/^"|"$/g, "");
            else if (/creator\s*tip/i.test(label)) ep.creatorTip = value;
            else ep.meta[strip(kv[1])] = value;
            continue;
          }
          // Dialogue: **CHARACTER:** "line" or CHARACTER: "line"
          const dlg = l.match(/^\*?\*?([A-Z][A-Z\s'()&,.]+?)\*?\*?\s*:\s*"(.+)"$/);
          if (dlg) { ep.dialogue.push({ type: "dialogue", character: dlg[1].trim(), line: dlg[2] }); continue; }
          // Stage direction [brackets]
          if (l.startsWith("[") && l.endsWith("]")) { ep.dialogue.push({ type: "direction", text: l.slice(1, -1) }); continue; }
          if (l.startsWith("(") && l.endsWith(")")) { ep.dialogue.push({ type: "direction", text: l }); continue; }
          // Fallback metadata
          const plainKv = l.match(/^([A-Z][A-Za-z\s]+):\s*(.*)/);
          if (plainKv && !l.startsWith("##")) { ep.meta[plainKv[1]] = plainKv[2]; continue; }
        }
        blocks.push(ep);
        continue;
      }

      // Named section (## Production Bible, ## CAST, etc.)
      if (lines[0].startsWith("## ")) {
        blocks.push({ type: "section", title: lines[0].replace("## ", ""), lines: lines.slice(1) });
        continue;
      }

      // Header block (has SERIES TITLE or GENRE or TAGLINE)
      const hasHeaderField = lines.some(l => /^(SERIES TITLE|GENRE|TAGLINE|LOGLINE|TOTAL EPISODES)/i.test(l));
      if (hasHeaderField) {
        const fields: Record<string, string> = {};
        for (const l of lines) {
          const m = l.match(/^([A-Z][A-Z\s]+?):\s*(.*)/);
          if (m) fields[m[1].trim()] = m[2];
        }
        blocks.push({ type: "header", fields });
        continue;
      }

      // Generic text block
      blocks.push({ type: "text", lines });
    }

    return blocks;
  };

  // ── Pass 2: Render blocks ──
  const renderScript = () => {
    if (!script) return null;
    const blocks = parseScript(script);

    return blocks.map((block, i) => {
      switch (block.type) {
        case "header": return <ScriptHeader key={i} fields={block.fields} />;
        case "episode": return <EpisodeCard key={i} ep={block} />;
        case "section": return <ProductionSection key={i} title={block.title} lines={block.lines} />;
        case "text": return <TextBlock key={i} lines={block.lines} />;
      }
    });
  };

  // ── Series Header ──
  const ScriptHeader = ({ fields }: { fields: Record<string, string> }) => {
    const title = fields["SERIES TITLE"] || "";
    const tagline = fields["TAGLINE"] || "";
    const genre = fields["GENRE"] || "";
    const eps = fields["TOTAL EPISODES"] || "";
    const dur = fields["EPISODE DURATION"] || "";
    const logline = fields["LOGLINE"] || "";
    const caption = fields["FIRST CAPTION"] || "";
    const tags = [genre, eps && `${eps} episodes`, dur].filter(Boolean);

    return (
      <div className="text-center mb-10 pb-8 border-b border-border/20">
        {title && <h1 className="text-2xl sm:text-3xl font-bold text-foreground tracking-tight">{title}</h1>}
        {tagline && <p className="text-sm text-muted-foreground mt-2 italic">{tagline}</p>}
        {tags.length > 0 && (
          <div className="flex flex-wrap justify-center gap-2 mt-4">
            {tags.map((t, j) => (
              <span key={j} className="text-[11px] text-muted-foreground/60 bg-muted/40 rounded-full px-3 py-1">
                {t}
              </span>
            ))}
          </div>
        )}
        {logline && <p className="text-sm text-muted-foreground/80 mt-4 max-w-lg mx-auto leading-relaxed">{logline}</p>}
        {caption && (
          <p className="text-xs text-muted-foreground/50 mt-3 max-w-md mx-auto">{caption}</p>
        )}
      </div>
    );
  };

  // ── Episode Card ──
  const EpisodeCard = ({ ep }: { ep: Extract<Block, { type: "episode" }> }) => {
    const metaEntries = Object.entries(ep.meta);

    return (
      <div className="mb-12">
        {/* Episode header */}
        <div className="mb-5">
          <span className="text-[10px] font-medium uppercase tracking-[0.25em] text-muted-foreground/40">
            Episode {ep.number}
          </span>
          <h2 className="text-lg sm:text-xl font-semibold text-foreground mt-0.5 leading-snug">{ep.title}</h2>
        </div>

        {/* Meta grid */}
        {metaEntries.length > 0 && (
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-x-4 gap-y-2 mb-6">
            {metaEntries.map(([key, value], j) => (
              <div key={j} className="min-w-0">
                <p className="text-[10px] uppercase tracking-wider text-muted-foreground/40 mb-0.5 truncate">{key}</p>
                <p className="text-xs text-muted-foreground/80 leading-snug truncate">{value}</p>
              </div>
            ))}
          </div>
        )}

        {/* Dialogue */}
        {ep.dialogue.length > 0 && (
          <div className="space-y-1 my-6">
            {ep.dialogue.map((d, j) =>
              d.type === "dialogue" ? (
                <div key={j} className="py-1.5">
                  <p className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground/60 mb-0.5">
                    {d.character}
                  </p>
                  <p className="text-[14px] text-foreground/90 leading-relaxed pl-4">
                    &ldquo;{d.line}&rdquo;
                  </p>
                </div>
              ) : (
                <p key={j} className="text-xs italic text-muted-foreground/40 text-center py-2">
                  {d.text}
                </p>
              )
            )}
          </div>
        )}

        {/* Cliffhanger */}
        {ep.cliffhanger && (
          <div className="mt-6 pt-4 border-t border-border/15">
            <p className="text-[10px] uppercase tracking-[0.2em] text-muted-foreground/35 mb-1">Cliffhanger</p>
            <p className="text-sm text-foreground/90 leading-relaxed">{ep.cliffhanger}</p>
          </div>
        )}

        {/* Killer line */}
        {ep.killerLine && (
          <p className="text-sm italic text-foreground/70 mt-3 pl-4 border-l-2 border-muted-foreground/15">
            &ldquo;{ep.killerLine}&rdquo;
          </p>
        )}

        {/* Creator tip */}
        {ep.creatorTip && (
          <p className="text-[11px] text-muted-foreground/40 mt-3 italic">
            {ep.creatorTip}
          </p>
        )}
      </div>
    );
  };

  // ── Production Section ──
  const ProductionSection = ({ title, lines }: { title: string; lines: string[] }) => (
    <div className="mt-10 pt-8 border-t border-border/20">
      <h3 className="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground/50 mb-5">{title}</h3>
      <div className="space-y-1.5">
        {lines.map((l, j) => {
          if (l.startsWith("- ")) {
            return (
              <div key={j} className="flex gap-2 text-sm text-muted-foreground/70">
                <span className="text-muted-foreground/25 shrink-0 mt-0.5">-</span>
                <span className="leading-relaxed">{renderInline(l.substring(2))}</span>
              </div>
            );
          }
          const kv = l.match(/^\*\*(.+?):\*\*\s*(.*)/);
          if (kv) {
            return (
              <p key={j} className="text-sm text-muted-foreground/70 my-1">
                <span className="font-medium text-muted-foreground/90">{strip(kv[1])}:</span>{" "}
                {kv[2]}
              </p>
            );
          }
          if (l.startsWith("**") && l.endsWith("**")) {
            return <p key={j} className="font-semibold text-muted-foreground/80 text-sm mt-4 mb-1">{strip(l)}</p>;
          }
          return <p key={j} className="text-sm text-muted-foreground/60 leading-relaxed">{renderInline(l)}</p>;
        })}
      </div>
    </div>
  );

  // ── Generic Text Block ──
  const TextBlock = ({ lines }: { lines: string[] }) => (
    <div className="my-4 space-y-1.5">
      {lines.map((l, j) => (
        <p key={j} className="text-sm text-muted-foreground/70 leading-relaxed">{renderInline(l)}</p>
      ))}
    </div>
  );

  const activeCat = categories.find((c) => c.label === activeCategory);

  return (
    <div className="min-h-screen">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
        <div className="flex gap-6">
          {/* Category Sidebar */}
          <aside className="hidden md:block w-56 shrink-0">
            <div className="sticky top-24">
              <h2 className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-3 px-2">
                Categories
              </h2>
              <nav className="space-y-1">
                {categories.map((cat) => (
                  <button
                    key={cat.label}
                    onClick={() =>
                      setActiveCategory(
                        activeCategory === cat.label ? null : cat.label
                      )
                    }
                    className={cn(
                      "w-full flex items-center gap-2.5 px-3 py-2.5 rounded-lg text-sm font-medium transition-all text-left",
                      activeCategory === cat.label
                        ? "bg-muted text-foreground border border-border"
                        : "text-muted-foreground hover:text-foreground hover:bg-muted border border-transparent"
                    )}
                  >
                    <span className="text-base">{cat.icon}</span>
                    {cat.label}
                  </button>
                ))}
              </nav>
            </div>
          </aside>

          {/* Main Content */}
          <div className="flex-1 min-w-0">
            {/* Header */}
            <div className="mb-6">
              <h1 className="text-2xl sm:text-3xl font-bold">
                <span className="text-accent">Generate</span> Your Script
              </h1>
              <p className="text-muted-foreground mt-1">
                Pick a category or describe your own drama concept.
              </p>
            </div>

            {/* Mobile Category Chips */}
            <div className="md:hidden flex gap-2 overflow-x-auto pb-3 mb-4 scrollbar-none">
              {categories.map((cat) => (
                <button
                  key={cat.label}
                  onClick={() =>
                    setActiveCategory(
                      activeCategory === cat.label ? null : cat.label
                    )
                  }
                  className={cn(
                    "flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium whitespace-nowrap border transition-all shrink-0",
                    activeCategory === cat.label
                      ? "bg-muted text-foreground border-border"
                      : "text-muted-foreground border-border hover:border-primary/30 hover:text-foreground"
                  )}
                >
                  <span>{cat.icon}</span>
                  {cat.label}
                </button>
              ))}
            </div>

            {/* Category Prompt Suggestions */}
            {activeCat && (
              <div className="rounded-xl border border-border bg-muted/50 p-4 mb-6">
                <p className="text-xs font-semibold text-foreground mb-2.5">
                  {activeCat.icon} {activeCat.label} — Quick Prompts
                </p>
                <div className="flex flex-wrap gap-2">
                  {activeCat.prompts.map((p) => (
                    <button
                      key={p}
                      onClick={() => {
                        setPrompt(p);
                      }}
                      className="px-3 py-1.5 text-xs rounded-lg border border-border bg-background text-muted-foreground hover:text-foreground hover:bg-muted transition-colors cursor-pointer"
                    >
                      <Play className="h-3 w-3 inline mr-1" />
                      {p}
                    </button>
                  ))}
                </div>
              </div>
            )}

            {/* Input Form */}
            <div className="rounded-xl border border-border bg-card p-4 sm:p-6 mb-8">
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.shiftKey) {
                    e.preventDefault();
                    handleGenerate();
                  }
                }}
                placeholder={
                  activeCat
                    ? `Describe your ${activeCat.label.toLowerCase()} drama concept...`
                    : 'e.g. "Two best friends, one betrayal, a friendship that might not survive"'
                }
                className="w-full bg-muted/50 text-foreground placeholder:text-muted-foreground rounded-lg px-4 py-3 text-base focus:outline-none focus:ring-2 focus:ring-primary/50 min-h-[80px] resize-none border border-border"
                rows={3}
                maxLength={500}
                aria-label="Drama concept input"
              />
              <div className="flex items-center justify-between mt-4 gap-4 flex-wrap">
                <div className="flex items-center gap-3">
                  {remaining !== null && (() => {
                    const r = Number(remaining);
                    const used = limit - r;
                    return (
                      <div className="flex items-center gap-2.5">
                        {isPro && <Crown className="h-3.5 w-3.5 text-accent shrink-0" />}
                        <div className="flex items-center gap-2">
                          <div className={`${isPro ? "w-24" : "w-16"} h-2 rounded-full bg-muted overflow-hidden`}>
                            <div
                              className={`h-full rounded-full transition-all ${isPro ? "bg-accent" : "bg-foreground/60"}`}
                              style={{ width: `${Math.min(100, (used / limit) * 100)}%` }}
                            />
                          </div>
                          <span className="text-xs text-muted-foreground whitespace-nowrap">
                            {used}/{limit}{isPro ? "/mo" : " today"}
                          </span>
                        </div>
                        {!isPro && (
                          <button
                            onClick={() => router.push("/pricing")}
                            className="text-xs text-accent hover:underline cursor-pointer"
                          >
                            Upgrade
                          </button>
                        )}
                      </div>
                    );
                  })()}
                </div>
                <div className="flex items-center gap-2 flex-wrap">
                  {/* Episodes selector */}
                  <div className="flex items-center gap-1.5">
                    <label htmlFor="episodes" className="text-xs text-muted-foreground whitespace-nowrap">
                      Episodes
                    </label>
                    <select
                      id="episodes"
                      value={episodes}
                      onChange={(e) => setEpisodes(Number(e.target.value))}
                      className="h-9 rounded-lg border border-border bg-muted/50 px-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 cursor-pointer"
                    >
                      {[4, 6, 8, 10, 12].map((n) => (
                        <option key={n} value={n}>
                          {n}
                        </option>
                      ))}
                    </select>
                  </div>

                  {/* Duration selector */}
                  <div className="flex items-center gap-1.5">
                    <label htmlFor="duration" className="text-xs text-muted-foreground whitespace-nowrap">
                      Duration
                    </label>
                    <select
                      id="duration"
                      value={duration}
                      onChange={(e) => setDuration(e.target.value)}
                      className="h-9 rounded-lg border border-border bg-muted/50 px-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 cursor-pointer"
                    >
                      <option value="15-30">15–30s</option>
                      <option value="30-60">30–60s</option>
                      <option value="60-90">60–90s</option>
                      <option value="90-120">90–120s</option>
                    </select>
                  </div>

                  <Button
                    onClick={() => handleGenerate()}
                    disabled={!prompt.trim() || loading}
                    variant="default"
                    size="lg"
                  >
                    {loading ? (
                      <>
                        <Loader2 className="h-4 w-4 animate-spin" />
                        Generating...
                      </>
                    ) : (
                      <>
                        <Zap className="h-4 w-4" />
                        Generate Script
                        <ArrowRight className="h-4 w-4" />
                      </>
                    )}
                  </Button>
                </div>
              </div>
            </div>

            {/* Error */}
            {error && (
              <div role="alert" className="rounded-xl border border-destructive/50 bg-destructive/10 p-4 mb-8 flex items-start gap-3">
                <AlertCircle className="h-5 w-5 text-destructive shrink-0 mt-0.5" />
                <div>
                  <p className="text-sm text-destructive font-medium">{error}</p>
                  {remaining === 0 && !isPro && (
                    <Button
                      variant="outline"
                      size="sm"
                      className="mt-2"
                      onClick={() => router.push("/pricing")}
                    >
                      <Crown className="h-3 w-3 mr-1" />
                      Upgrade to Pro — ₹499/month
                    </Button>
                  )}
                </div>
              </div>
            )}

            {/* Loading State */}
            {loading && (
              <div className="rounded-xl border border-border bg-card p-12 text-center" role="status" aria-busy="true">
                <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-muted mb-4">
                  <Loader2 className="h-8 w-8 text-muted-foreground animate-spin" />
                </div>
                <h3 className="text-lg font-bold mb-2">Writing your drama...</h3>
                <p className="text-sm text-muted-foreground">
                  Crafting 8 episodes with emotional hooks, plot twists, and cliffhangers
                </p>
                <div className="flex justify-center gap-1 mt-4">
                  {[0, 1, 2, 3, 4].map((i) => (
                    <div
                      key={i}
                      className="w-2 h-2 rounded-full bg-muted-foreground animate-pulse"
                      style={{ animationDelay: `${i * 0.3}s` }}
                    />
                  ))}
                </div>
              </div>
            )}

            {/* Empty State */}
            {!script && !loading && !error && !initialPrompt && !activeCat && (
              <div className="rounded-xl border border-border/50 border-dashed bg-card/30 p-8 sm:p-12 text-center">
                <div className="inline-flex items-center justify-center w-14 h-14 rounded-full bg-muted mb-4">
                  <Sparkles className="h-7 w-7 text-accent" />
                </div>
                <h3 className="text-lg font-bold mb-2">Your script will appear here</h3>
                <p className="text-sm text-muted-foreground mb-6 max-w-md mx-auto">
                  Pick a category from the left, or type your own concept above.
                </p>
                <div className="flex flex-wrap justify-center gap-2">
                  {categories.slice(0, 4).map((cat) => (
                    <button
                      key={cat.label}
                      onClick={() => setActiveCategory(cat.label)}
                      className="px-3 py-1.5 text-xs sm:text-sm rounded-full border border-border bg-muted/50 text-muted-foreground hover:text-foreground hover:border-border hover:bg-muted transition-all cursor-pointer"
                    >
                      <span className="mr-1">{cat.icon}</span>
                      {cat.label}
                    </button>
                  ))}
                </div>
              </div>
            )}

            {/* Script Output */}
            {script && !loading && (
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <h2 className="text-lg font-semibold flex items-center gap-2">
                    <Sparkles className="h-4 w-4 text-muted-foreground" />
                    Your Script is Ready
                  </h2>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={handleCopy}>
                      {copied ? (
                        <>
                          <Check className="h-3.5 w-3.5" />
                          Copied!
                        </>
                      ) : (
                        <>
                          <Copy className="h-3.5 w-3.5" />
                          Copy All
                        </>
                      )}
                    </Button>
                    <Button variant="secondary" size="sm" onClick={handlePDF} disabled={pdfLoading}>
                      {pdfLoading ? (
                        <Loader2 className="h-3.5 w-3.5 animate-spin" />
                      ) : (
                        <FileDown className="h-3.5 w-3.5" />
                      )}
                      Export PDF
                    </Button>
                  </div>
                </div>

                <div
                  ref={scriptRef}
                  className="rounded-2xl border border-border/40 bg-card px-6 py-8 sm:px-10 sm:py-10 overflow-y-auto max-h-[80vh]"
                >
                  {renderScript()}
                </div>

                <div className="text-center pt-4 space-y-3">
                  <p className="text-sm text-muted-foreground">
                    Want a different take? Edit the prompt and generate again.
                  </p>
                  <div className="flex justify-center gap-3">
                    <Button
                      variant="outline"
                      onClick={() => {
                        setScript("");
                        setGenerationId(null);
                        window.scrollTo({ top: 0, behavior: "smooth" });
                      }}
                    >
                      Generate Another Script
                    </Button>
                    {generationId && (
                      <Link href="/dashboard">
                        <Button variant="secondary">
                          <LayoutDashboard className="h-3.5 w-3.5" />
                          View in Dashboard
                        </Button>
                      </Link>
                    )}
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
