import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — DramaScript.ai",
  description: "Terms of Service for DramaScript.ai — AI short drama script generator.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-12 sm:py-20">
      <h1 className="text-3xl font-bold mb-8">
        Terms of <span className="text-accent">Service</span>
      </h1>

      <div className="prose prose-invert prose-sm max-w-none space-y-6 text-muted-foreground">
        <p className="text-foreground text-base">
          Last updated: April 2026. By using DramaScript.ai, you agree to these terms.
        </p>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-foreground">1. Service Description</h2>
          <p>
            DramaScript.ai is an AI-powered script generation tool that creates short drama scripts
            for social media content creators. The service generates 8-episode story arcs with
            dialogue, filming guides, and emotional hooks optimized for Reels, TikTok, and YouTube Shorts.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-foreground">2. Usage Rights</h2>
          <p>
            All scripts generated through DramaScript.ai are owned by you, the user. You are free to
            use, edit, publish, and monetize any generated scripts on any platform. We claim no
            ownership or copyright over generated content.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-foreground">3. Free & Pro Plans</h2>
          <p>
            <strong className="text-foreground">Free Plan:</strong> 3 script generations per day. No account
            required. Subject to rate limiting.
          </p>
          <p>
            <strong className="text-foreground">Pro Plan (&#8377;499/month):</strong> Unlimited script
            generations for 30 days from the date of payment. This is a one-time payment, not an
            auto-renewing subscription. To continue after 30 days, you must make a new payment.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-foreground">4. Payments & Refunds</h2>
          <p>
            Payments are processed securely through Razorpay. We accept credit/debit cards, UPI, and
            net banking. All prices are inclusive of applicable taxes.
          </p>
          <p>
            Refunds are available within 7 days of purchase if you are unsatisfied with the service.
            Contact us at the email below for refund requests.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-foreground">5. Acceptable Use</h2>
          <p>You agree not to use DramaScript.ai to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Generate content that promotes hate speech, violence, or discrimination</li>
            <li>Generate explicit adult content</li>
            <li>Abuse the free tier through automated or bot-driven requests</li>
            <li>Attempt to reverse-engineer or extract the AI prompts used by the service</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-foreground">6. AI-Generated Content Disclaimer</h2>
          <p>
            Scripts are generated by artificial intelligence and may occasionally produce inaccurate,
            culturally insensitive, or unexpected content. You are responsible for reviewing and
            editing all generated scripts before publishing. DramaScript.ai is not liable for any
            consequences arising from the use of generated content.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-foreground">7. Limitation of Liability</h2>
          <p>
            DramaScript.ai is provided &ldquo;as is&rdquo; without warranties of any kind. We are not
            liable for any damages arising from your use of the service, including but not limited to
            loss of revenue, data, or content.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-foreground">8. Changes to Terms</h2>
          <p>
            We may update these terms from time to time. Continued use of the service constitutes
            acceptance of updated terms.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-foreground">9. Contact</h2>
          <p>
            For questions about these terms, email us at{" "}
            <span className="text-accent">support@dramascript.ai</span>
          </p>
        </section>
      </div>
    </div>
  );
}
